server:
  port:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
mybatis-plus:
  type-aliases-package: top.sakwya.Jwork.domain